name: demo_pipeline
argo_version_lock: true
#cluster_name at the pipeline level means that every step in the pipeline will deploy to cluster_local.
#If cluster_name is also defined at a particular step, it will override the cluster_name set at the pipeline
#(only for that step).
cluster_name: in-cluster
steps:
- name: run_jenkins_job
  tests:
  - path: tasks/run_jenkins_job.py
    type: inject
    image: python:latest
    commands: [/bin/bash, -c, pip install python-jenkins && python run_jenkins_job.py]
    before: false
    variables:
      - name: JENKINS_URL
        value: http://jenkins.jenkins.svc.cluster.local:8080
      - name: JOB_NAME
        value: test
      - name: TOKEN_NAME
        valueFrom:
          secretKeyRef:
            name: jenkins-token-secret
            key: password
- name: deploy_to_dev
  application_path: testapp_int.yml
  rollback_limit: 1
  tests:
  - path: tasks/run_java_task1.yaml
    type: custom
    before: true
  - path: tasks/HelloWorld.java
    type: inject
    image: java:latest
    commands: [/bin/bash, -c, javac HelloWorld.java && java HelloWorld]
    before: true
  #The schema is DAG based, allowing both linear and complex pipelines
  dependencies:
  - run_jenkins_job
