name: demo_pipeline
argo_version_lock: true
#cluster_name at the pipeline level means that every step in the pipeline will deploy to cluster_local.
#If cluster_name is also defined at a particular step, it will override the cluster_name set at the pipeline
#(only for that step).
cluster_name: in-cluster
steps:
- name: run_jenkins_job
  tests:
  - path: tasks/run_jenkins_job.py
    type: inject
    image: python:latest
    commands: [/bin/bash, -c, pip install python-jenkins && python run_jenkins_job.py]
    before: false
    variables:
      - name: JENKINS_URL
        value: http://jenkins.jenkins.svc.cluster.local:8080
      - name: JOB_NAME
        value: test
      - name: TOKEN_NAME
        valueFrom:
          secretKeyRef:
            name: jenkins-token-secret
            key: password
- name: deploy_to_staging
  application_path: testapp_dev.yml
  tests:
  - path: tasks/smoke_test.sh
    type: inject
    image: curlimages/curl:latest
    commands: [sh, -c, ./smoke_test.sh]
    before: false
    variables:
      - name: SERVICE_INTERNAL_URL
        value: testapp.staging.svc.cluster.local
  #The schema is DAG based, allowing both linear and complex pipelines
  dependencies:
  - run_jenkins_job
- name: deploy_to_prod
  application_path: testapp_int.yml
  rollback_limit: 1
  tests:
  - path: tasks/smoke_test.sh
    type: inject
    image: curlimages/curl:latest
    commands: [sh, -c, ./smoke_test.sh]
    before: false
    variables:
      - name: SERVICE_INTERNAL_URL
        value: testapp.prod.svc.cluster.local
  dependencies:
  - deploy_to_staging
