apiVersion: batch/v1
kind: Job
metadata:
  name: java-task
spec:
  template:
    spec:
      containers:
      - name: helloworld
        image: helloworld-image
        imagePullPolicy: Never
      restartPolicy: Never
